baseURL = 'http://localhost:1313/'
languageCode = 'en'
title = 'Real Money Slots Online 2022. Play Slots And Win Real Money!'
theme = 'basic'
DefaultContentLanguage = 'gb'

[params]
  favicon = 'images/favicons/icon-57.png'
  logo = 'images/logo.png'
  footerLogo = 'images/logo_footer.png'
  description = "Play real money slots online➡ with exclusive bonuses✅ offered by the best casinos✅ – Find detailed reviews of casino games with winning tips and make cash gambling"
  twitter_handle = 'Languages'
  keywords = 'slot, casino'
  author = 'Barnaba Bianchi'
  siteName = 'BestMoneySlots'
  copyright = "BestMoneySlots | All rights reserved."
  email = "contact@bestmoneyslots.com"

[languages]
  [languages.gb]
    languageName = 'English'
    weight = 1
  [languages.ru]
    languageName = 'Русский'
    weight = 2
    title = 'Слоты на реальные деньги онлайн 2022. Играйте в слоты и выигрывайте реальные деньги!'
    description = 'Играйте в слоты на реальные деньги онлайн➡ с эксклюзивными бонусами✅, предлагаемыми лучшими казино✅ - Найдите подробные обзоры игр казино с советами по выигрышу и зарабатывайте деньги на азартных играх'

[menu]
  [[menu.main]]
    name = 'Free Slots'
    pageref = '/slot'
    weight = 1
    [menu.main.params]
      icon = "images/icons/nav-slot.svg"
  [[menu.main]]
    name = 'Casinos'
    pageref = '/casino'
    [menu.main.params]
      icon = "images/icons/nav-chip.svg"

[taxonomies]
  category = 'categories'
  software = 'software'
  tag = 'tags'