baseURL = '/'
languageCode = 'en'
title = 'Real Money Slots Online 2022. Play Slots And Win Real Money!'
theme = 'basic'
DefaultContentLanguage = 'gb'

summaryLength = 30

[params]
  mainSections = ['casino', 'slots', 'software']
  favicon = 'images/favicons/icon-57.png'
  logo = 'images/logo.png'
  defaultImg = '/images/default.png'
  footerLogo = 'images/logo_footer.png'
  description = "Play real money slots online➡ with exclusive bonuses✅ offered by the best casinos✅ – Find detailed reviews of casino games with winning tips and make cash gambling"
  keywords = 'slot, casino'
  author = 'Barnaba Bianchi'
  siteName = 'BestMoneySlots'
  copyright = "BestMoneySlots | All rights reserved."
  email = "contact@bestmoneyslots.com"
  referral = 'https://redirectid.com/click.php?key=42t5uehm7vx8tk6nibtr&split='


[languages.gb]
  languageName = 'English'
  weight = 1

[[languages.gb.menu.main]]
  name = 'Free Slots'
  pageref = '/slots'
  weight = 1
  [languages.gb.menu.main.params]
    icon = "images/icons/nav-slot.svg"

[[languages.gb.menu.main]]
  name = 'Casinos'
  pageref = '/casino'
  weight = 2
  [languages.gb.menu.main.params]
      icon = "images/icons/nav-chip.svg"

[[languages.gb.menu.main]]
  name = 'Blog'
  pageref = '/blog'
  weight = 3
  [languages.gb.menu.main.params]
      icon = "images/icons/nav-bonus.svg"

# FOOTER 1 MENU
[[languages.gb.menu.footer]]
  name = 'Free Slots'
  pageref = '/slots'
  weight = 1

# FOOTER 2 MENU
[[languages.gb.menu.second]]
  name = 'Free Slosts'
  pageref = '/slots'
  weight = 1

# FOOTER 3 MENU
[[languages.gb.menu.three]]
  name = 'Free Slosts'
  pageref = '/slots'
  weight = 1


[languages.ru]
  languageName = 'Русский'
  weight = 2
  title = 'Слоты на реальные деньги онлайн 2022. Играйте в слоты и выигрывайте реальные деньги!'
  description = 'Играйте в слоты на реальные деньги онлайн➡ с эксклюзивными бонусами✅, предлагаемыми лучшими казино✅ - Найдите подробные обзоры игр казино с советами по выигрышу и зарабатывайте деньги на азартных играх'
[[languages.ru.menu.main]]
  url = '/ru/'
  name = 'Главная'
  weight = 1
  [languages.ru.menu.main.params]
    icon = "images/icons/nav-slot.svg"

[taxonomies]
  category = 'categories'
  software = 'software'
  tag = 'tags'

# [markup.goldmark.renderer]

#   unsafe = true
