baseURL = '/'
languageCode = 'en'
theme = 'basic'
DefaultContentLanguage = 'de'
enableRobotsTXT = true
disableHugoGeneratorInject = true
summaryLength = 30
paginate = 28

[params]
  mainSections = ['casino', 'slots', 'software']
  favicon = 'images/favicons/icon-57.png'
  logo = 'images/logo.png'
  defaultImg = '/images/default.png'
  footerLogo = 'images/logo_footer.png'
  author = 'Barnaba Bianchi'
  siteName = 'BestMoneySlots'
  referral = 'https://redirectid.com/click.php?key=42t5uehm7vx8tk6nibtr&split='
  CPU = 'https://bgcsavannah.org'
  


[languages.de]
  languageName = 'English'
  weight = 1

[[languages.de.menu.main]]
  name = 'Freie Slots'
  pageref = '/slots'
  weight = 1
  [languages.de.menu.main.params]
    icon = "images/icons/nav-slot.svg"

[[languages.de.menu.main]]
  name = 'Kasino'
  pageref = '/casino'
  weight = 2
  [languages.de.menu.main.params]
      icon = "images/icons/nav-chip.svg"

[[languages.de.menu.main]]
  name = 'Bloggen'
  pageref = '/blog'
  weight = 3
  [languages.de.menu.main.params]
      icon = "images/icons/nav-bonus.svg"
[[languages.de.menu.main]]
  name = 'Software'
  pageref = '/software'
  weight = 4
  [languages.de.menu.main.params]
      icon = "images/icons/nav-slot.svg"

# FOOTER 1 MENU
[[languages.de.menu.footer]]
  name = 'Book of RA'
  pageref = '/slots/book-of-ra'
  weight = 1
[[languages.de.menu.footer]]
  name = 'Eye of Horus'
  pageref = '/slots/eye-of-horus'
  weight = 1
[[languages.de.menu.footer]]
  name = 'Book of Dead'
  pageref = '/slots/book-of-dead'
  weight = 1
[[languages.de.menu.footer]]
  name = 'Sweet Bonanza'
  pageref = '/slots/sweet-bonanza'
  weight = 1
[[languages.de.menu.footer]]
  name = 'Big Bass Bonanza'
  pageref = '/slots/big-bass-bonanza'
  weight = 1

# FOOTER 2 MENU
[[languages.de.menu.second]]
  name = 'ICE Casino'
  pageref = '/casino/ice-casino'
  weight = 1
[[languages.de.menu.second]]
  name = 'Vulkan Vegas'
  pageref = '/casino/vulkan-vegas'
  weight = 1
[[languages.de.menu.second]]
  name = 'GGBet'
  pageref = '/casino/ggbet'
  weight = 1

# FOOTER 3 MENU
[[languages.de.menu.three]]
  name = 'Yggdrasil'
  pageref = '/software/yggdrasil'
  weight = 1
[[languages.de.menu.three]]
  name = 'Blueprint'
  pageref = '/software/blueprint'
  weight = 1
[[languages.de.menu.three]]
  name = 'Pragmatic Play'
  pageref = '/software/pragmatic-play'
  weight = 1
[[languages.de.menu.three]]
  name = 'Novomatic'
  pageref = '/software/novomatic'
  weight = 1
[[languages.de.menu.three]]
  name = 'Evolution Gaming'
  pageref = '/software/evolution-gaming'
  weight = 1
[[languages.de.menu.three]]
  name = 'Aristocrat'
  pageref = '/software/aristocrat'
  weight = 1
[[languages.de.menu.three]]
  name = 'IGT'
  pageref = '/software/igt'
  weight = 1
[[languages.de.menu.three]]
  name = 'Nextgen'
  pageref = '/software/nextgen'
  weight = 1

#
#[languages.ru]
#  languageName = 'Русский'
#  weight = 2
#  title = 'Слоты на реальные деньги онлайн 2022. Играйте в слоты и выигрывайте реальные деньги!'
#  description = 'Играйте в слоты на реальные деньги онлайн➡ с эксклюзивными бонусами✅, предлагаемыми лучшими казино✅ - Найдите подробные обзоры игр казино с советами по выигрышу и зарабатывайте деньги на азартных играх'
# [[languages.ru.menu.main]]
#  url = '/ru/'
#  name = 'Главная'
#  weight = 1
#  [languages.ru.menu.main.params]
#    icon = "images/icons/nav-slot.svg"


[taxonomies]
  software = 'software'

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 2